-- CATEGORY ------------------------------------------------------------------------------------------------------------------------------------------

CREATE TABLE CATEGORY (
  NAME TEXT CONSTRAINT PK_CATEGORY PRIMARY KEY,
  SHORT_NAME TEXT NOT NULL,
  DESCRIPTION TEXT
);

-- USER ----------------------------------------------------------------------------------------------------------------------------------------------

CREATE TABLE "USER" (
  USERNAME TEXT CONSTRAINT PK_USER PRIMARY KEY,
  EMAIL TEXT NOT NULL,
  SALT TEXT NOT NULL,
  PASSWORD_HASH TEXT NOT NULL,
  IS_SUDO BOOLEAN NOT NULL DEFAULT FALSE,
  IS_VERIFIED BOOLEAN NOT NULL DEFAULT FALSE,
  SPECIAL_NAME TEXT

  CONSTRAINT USER_IF_IS_NOT_VERIFIED_DO_NOT_ALLOW_SPECIAL_NAME
    CHECK ( NOT ( IS_VERIFIED = FALSE AND SPECIAL_NAME NOTNULL ) )
);

-- CATEGORY_ADMINS -----------------------------------------------------------------------------------------------------------------------------------

CREATE TABLE CATEGORY_ADMINS (
  "USER" TEXT NOT NULL,
  CATEGORY TEXT NOT NULL,
  CONSTRAINT PK_CATEGORY_ADMINS PRIMARY KEY ("USER", CATEGORY)
);

CREATE INDEX IDX_CATEGORY_ADMINS ON CATEGORY_ADMINS (CATEGORY);

ALTER TABLE CATEGORY_ADMINS ADD CONSTRAINT FK_CATEGORY_ADMINS__CATEGORY FOREIGN KEY (CATEGORY) REFERENCES CATEGORY (NAME) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE CATEGORY_ADMINS ADD CONSTRAINT FK_CATEGORY_ADMINS__USER FOREIGN KEY ("USER") REFERENCES "USER" (USERNAME) ON DELETE CASCADE ON UPDATE CASCADE;

-- CATEGORY_FOLLOWERS --------------------------------------------------------------------------------------------------------------------------------

CREATE TABLE CATEGORY_FOLLOWERS (
  "USER" TEXT NOT NULL,
  CATEGORY TEXT NOT NULL,
  CONSTRAINT PK_CATEGORY_FOLLOWERS PRIMARY KEY ("USER", CATEGORY)
);

CREATE INDEX IDX_CATEGORY_FOLLOWERS ON CATEGORY_FOLLOWERS (CATEGORY);

ALTER TABLE CATEGORY_FOLLOWERS ADD CONSTRAINT FK_CATEGORY_FOLLOWERS__CATEGORY FOREIGN KEY (CATEGORY) REFERENCES CATEGORY (NAME) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE CATEGORY_FOLLOWERS ADD CONSTRAINT FK_CATEGORY_FOLLOWERS__USER FOREIGN KEY ("USER") REFERENCES "USER" (USERNAME) ON DELETE CASCADE ON UPDATE CASCADE;

-- DEVICE --------------------------------------------------------------------------------------------------------------------------------------------

CREATE TABLE DEVICE (
  ID SERIAL CONSTRAINT PK_DEVICE PRIMARY KEY,
  "USER" TEXT NOT NULL,
  NAME TEXT,
  UUID UUID NOT NULL UNIQUE,
  IS_CURRENTLY_USED BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE INDEX IDX_DEVICE__USER ON DEVICE ("USER");

ALTER TABLE DEVICE ADD CONSTRAINT FK_DEVICE__USER FOREIGN KEY ("USER") REFERENCES "USER" (USERNAME) ON DELETE CASCADE ON UPDATE CASCADE;

-- POST ----------------------------------------------------------------------------------------------------------------------------------------------

CREATE TABLE POST (
  ID SERIAL CONSTRAINT PK_POST PRIMARY KEY,
  TITLE TEXT,
  CONTEXT TEXT NOT NULL,
  POSTER TEXT NOT NULL,
  DATETIME TIMESTAMP NOT NULL,
  CATEGORY TEXT NOT NULL,
  PARENT INT,
  IS_CANDIDATE_FOR_DELETION BOOLEAN DEFAULT FALSE
);

CREATE INDEX IDX_POST__CATEGORY ON POST (CATEGORY);

CREATE INDEX IDX_POST__PARENT ON POST (PARENT);

CREATE INDEX IDX_POST__POSTER ON POST (POSTER);

ALTER TABLE POST ADD CONSTRAINT FK_POST__CATEGORY FOREIGN KEY (CATEGORY) REFERENCES CATEGORY (NAME) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE POST ADD CONSTRAINT FK_POST__PARENT FOREIGN KEY (PARENT) REFERENCES POST (ID) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE POST ADD CONSTRAINT FK_POST__POSTER FOREIGN KEY (POSTER) REFERENCES "USER" (USERNAME) ON DELETE NO ACTION ON UPDATE CASCADE;

ALTER TABLE POST ADD COLUMN IS_EDITED BOOLEAN DEFAULT FALSE;

-- POST_DISLIKERS ------------------------------------------------------------------------------------------------------------------------------------

CREATE TABLE POST_DISLIKERS (
  "USER" TEXT NOT NULL,
  POST INT NOT NULL,
  CONSTRAINT PK_POST_DISLIKERS PRIMARY KEY ("USER", POST)
);

CREATE INDEX IDX_POST_DISLIKERS ON POST_DISLIKERS (POST);

ALTER TABLE POST_DISLIKERS ADD CONSTRAINT FK_POST_DISLIKERS__POST FOREIGN KEY (POST) REFERENCES POST (ID) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE POST_DISLIKERS ADD CONSTRAINT FK_POST_DISLIKERS__USER FOREIGN KEY ("USER") REFERENCES "USER" (USERNAME) ON DELETE CASCADE ON UPDATE CASCADE;

-- POST_LIKERS ---------------------------------------------------------------------------------------------------------------------------------------

CREATE TABLE POST_LIKERS (
  "USER" TEXT NOT NULL,
  POST INT NOT NULL,
  CONSTRAINT PK_POST_LIKERS PRIMARY KEY ("USER", POST)
);

CREATE INDEX IDX_POST_LIKERS ON POST_LIKERS (POST);

ALTER TABLE POST_LIKERS ADD CONSTRAINT FK_POST_LIKERS__POST FOREIGN KEY (POST) REFERENCES POST (ID) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE POST_LIKERS ADD CONSTRAINT FK_POST_LIKERS__USER FOREIGN KEY ("USER") REFERENCES "USER" (USERNAME) ON DELETE CASCADE ON UPDATE CASCADE;